
# DataSource Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demos?useUnicode=true&characterEncoding=UTF-8&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
